@startuml
title <size:24>Notification Services</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("PersonalApplication_boundary", "PersonalApplication", $tags="") {
  Container_Boundary("PersonalApplication.PersonalApplication_boundary", "PersonalApplication", $tags="") {
    Component(PersonalApplication.PersonalApplication.TriviaQuiz, "Trivia Quiz", $techn="Module", $descr="", $tags="", $link="")
    Component(PersonalApplication.PersonalApplication.UserManagement, "User Management", $techn="Module", $descr="", $tags="", $link="")
    Component(PersonalApplication.PersonalApplication.NotificationServices, "Notification Services", $techn="Module", $descr="", $tags="", $link="")
    Component(PersonalApplication.PersonalApplication.Booking, "Booking", $techn="Module", $descr="", $tags="", $link="")
    Component(PersonalApplication.PersonalApplication.Foosball, "Foosball", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(PersonalApplication.PersonalApplication.NotificationServices, PersonalApplication.PersonalApplication.TriviaQuiz, "listens to", $techn="", $tags="", $link="")
Rel(PersonalApplication.PersonalApplication.NotificationServices, PersonalApplication.PersonalApplication.Foosball, "listens to", $techn="", $tags="", $link="")
Rel(PersonalApplication.PersonalApplication.NotificationServices, PersonalApplication.PersonalApplication.UserManagement, "listens to", $techn="", $tags="", $link="")
Rel(PersonalApplication.PersonalApplication.NotificationServices, PersonalApplication.PersonalApplication.Booking, "listens to", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml