spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbmaster
    username: dbmasteruser
    password:

  liquibase:
    url: jdbc:postgresql://localhost:5432/dbmaster
    user: dbmasteruser
    password:
    contexts: dev

  # DevTools configuration for hot reload
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources
    livereload:
      enabled: true

notification:
  email:
    enabled: false

calendar:
  nextcloud:
    enabled: false

skatetricks:
  vectorstore:
    enabled: false

posthog:
  enabled: ${PERSONAL_POSTHOG_ENABLED:false}
